const $=id=>document.getElementById(id), text=(id,value)=>$(id).textContent=value, json=x=>JSON.stringify(x,null,2);
let generation=0,chain=Promise.resolve(),inspection=null,session=null,focusVersion=0;
document.addEventListener('focusin',()=>++focusVersion);
const element=(tag,value)=>{const n=document.createElement(tag);n.textContent=value;return n;};
const unknown=x=>x===null||x===undefined?'Unknown':String(x);
const key=x=>[x.source_system,x.order,x.item,x.schedule_line].join(' / ');
function clear(){inspection=null;$('confirm').checked=false;$('confirm').disabled=true;$('review').disabled=true;$('receipt').disabled=true;$('desk').hidden=true;$('minimal').hidden=true;for(const id of ['lines','notes','timeline','queue','questions','history','quantities'])$(id).replaceChildren();for(const id of ['heading','authority','confirmed-date','event-summary','unknown-context','binding','minimal-status','minimal-owner'])text(id,'');text('source-evidence','No source record selected.');}
function failure(e){clear();text('status',e.code==='SOURCE_UNAVAILABLE'?'UNAVAILABLE · current source authority revoked. Fresh admission and inspection are required.':`${e.code??'UNAVAILABLE'} · ${e.message}`);}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Object.assign(Error(d.message??'View unavailable'),{code:d.error});return d;}
function enqueue(action,g=generation){chain=chain.catch(()=>{}).then(async()=>{if(g!==generation)return;try{await action(g);}catch(e){if(g===generation)failure(e);}});return chain;}
const locationQuery=()=>`order=${encodeURIComponent($('order').value)}&revision=${$('revision').value}`;
function sourceButton(id,label){const b=element('button',label);b.className='source-link';b.addEventListener('click',()=>{const g=generation,f=focusVersion;enqueue(async()=>{const record=await api(`/api/source?${locationQuery()}&id=${encodeURIComponent(id)}`);if(g!==generation)return;text('source-evidence',json(record));if(f===focusVersion)$('source-evidence').focus();},g);});return b;}
function render(d){clear();if(!d.view){text('minimal-status',d.status);text('minimal-owner',d.owner_role);$('minimal').hidden=false;text('status','PERMITTED STATUS · current fictional role projection');return;}
 inspection=d;const v=d.view,current=v.source_revision===d.current_source_revision;$('desk').hidden=false;text('heading',`${v.order} · schedule lines · source revision ${v.source_revision}`);text('authority',current?'CURRENT SOURCE VIEW':'HISTORICAL SOURCE VIEW');text('status',`${current?'CURRENT':'HISTORICAL'} · ${v.status} · no release decision`);
 for(const [field,label]of [['ordered_ea','Ordered EA'],['confirmed_ea','Confirmed EA'],['delivered_ea','Delivered EA'],['remaining_ordered_ea','Remaining ordered EA']]){const m=element('div','');m.className='metric';m.append(element('span',label),element('strong',unknown(v.quantities[field])));$('quantities').append(m);}
 text('confirmed-date',v.order_wide_confirmed_arrival_date?`Order-wide confirmed destination arrival: ${v.order_wide_confirmed_arrival_date}`:'No single order-wide confirmed destination arrival date.');
 for(const l of v.lines){const row=element('tr',''),cell=element('td','');cell.append(sourceButton(l.record_id,key(l.key)));row.append(cell);for(const f of ['ordered_ea','confirmed_ea','delivered_ea','remaining_ordered_ea','requested_destination_arrival_date','confirmed_destination_arrival_date','planned_dispatch_date','actual_delivery_date'])row.append(element('td',unknown(l[f])));$('lines').append(row);}
 for(const n of v.notes){const p=element('p',`${n.text} · ${n.recorded_at} · customer request only; no promise or release.`);p.append(sourceButton(n.record_id,'Inspect request source'));$('notes').append(p);}
 for(const c of v.restricted_context){const p=element('p','Fictional commercial-only source context: ');p.append(sourceButton(c.record_id,c.title));$('notes').append(p);}
 text('event-summary',`${v.event_summary.unique_event_count} unique source events · ${v.event_summary.transport_duplicate_count} transport duplicates · ${v.event_summary.block_instance_count} instances · ${v.active_blocks.length} active blocks`);
 for(const e of v.events){const li=element('li',`${e.at} · ${e.kind} · ${e.block_instance_id} · revision ${e.revision} `);li.append(sourceButton(e.event_id,e.event_id));$('timeline').append(li);}
 text('unknown-context',v.events.length?'A source clear affects its exact block instance. Local review never changes these events.':'No source event timeline was supplied for this order. A snapshot block has no invented opening event or time.');
 for(const b of v.active_blocks)$('queue').append(element('p',`${b.block_instance_id} · ${b.status} · responsible role: ${unknown(b.owner_role)} · ${key(b.key)}`));
 if(!v.active_blocks.length)$('queue').append(element('p','No active instance is present in this inspected source view. Unknown context remains unresolved.'));
 for(const q of v.unresolved_questions)$('questions').append(element('li',q));text('binding',d.binding?json(d.binding):'No reviewable instance binding.');
 for(const h of d.history){const currentReceipt=current&&h.origin==='executed_local_review'&&h.view_fingerprint===d.binding?.view_fingerprint&&h.role_revision===session.role_revision;const p=element('p',`${currentReceipt?'CURRENT LOCAL RECEIPT':'HISTORICAL RECEIPT'} · ${h.review_id} · ${h.block_instance_id} · revision ${h.source_revision} · ${h.origin==='seeded_fixture_history'?'fictional seeded history, not an executed app review':'executed local acknowledgment'} · no clear/release.`);$('history').append(p);}
 $('confirm').disabled=!d.review_enabled||!current;updateActions();
}
function updateActions(){const enabled=inspection?.review_enabled&&$('confirm').checked;$('review').disabled=!enabled;$('receipt').disabled=!enabled;}
async function load(g){const d=await api(`/api/order?${locationQuery()}`);if(g===generation)render(d);}
function inspect(){const g=++generation;clear();text('status','LOADING · inspecting exact selected role, order and revision');const role=$('role').value;enqueue(async()=>{if(session?.role!==role){const d=await api('/api/role',{role});session={...session,...d};if(g!==generation)return;}await load(g);},g);}
$('role').addEventListener('change',()=>inspect({roleChange:true}));for(const id of ['order','revision'])$(id).addEventListener('change',()=>inspect());$('refresh').addEventListener('click',()=>inspect());$('confirm').addEventListener('change',updateActions);
for(const id of ['review','receipt'])$(id).addEventListener('click',()=>{if(!inspection?.review_enabled||!$('confirm').checked)return;const g=generation,body={...inspection.binding,acknowledgment:true};$('review').disabled=true;$('receipt').disabled=true;enqueue(async()=>{const result=await api(`/api/${id}`,body);if(g!==generation)return;await load(g);if(g!==generation)return;text('status',id==='receipt'?'EXPORT PREPARED / ACKNOWLEDGED · exact local receipt; download completion and target-system import are not established.':`${result.idempotent?'REPEATED ACKNOWLEDGMENT · existing receipt':'LOCAL REVIEW RECORDED'} · source blocks unchanged.`);if(id==='receipt'){text('source-evidence',json(result));const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([json(result)],{type:'application/json'}));link.download='fictional-handoff-receipt.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}},g);});
enqueue(async g=>{session=await api('/api/session');if(g!==generation)return;$('role').value=session.role;text('cutoff',`Source cutoff: ${session.source_cutoff} · ${session.source_timezone} · current admitted revision ${session.current_source_revision}`);await load(g);});
