"""Actual native Chrome checks; isolated admitted copies, CPU only, no model requests."""
import asyncio,json,os,shutil,subprocess,tempfile,urllib.request,hashlib
from pathlib import Path
from playwright.async_api import async_playwright,expect
ROOT=Path(__file__).resolve().parents[1];URL='http://127.0.0.1:5141'
async def main():
 checks=[];original=ROOT/'fixtures/source-v1.json';before=hashlib.sha256(original.read_bytes()).hexdigest();out=ROOT/'docs';out.mkdir(exist_ok=True)
 def checked(name,details=None):checks.append({'name':name,'passed':True,'details':details})
 with tempfile.TemporaryDirectory(prefix='p14-browser-owned-')as directory:
  source=Path(directory)/'source.json';policy=Path(directory)/'policy.json';shutil.copyfile(original,source);shutil.copyfile(ROOT/'fixtures/review-policy-v1.json',policy)
  server=subprocess.Popen(['node','--input-type=module','-e',"import {createDesk} from './server.mjs';(await createDesk({sourcePath:process.env.P14_SOURCE,policyPath:process.env.P14_POLICY})).listen(5141,'127.0.0.1')"],cwd=ROOT,env=dict(os.environ,P14_SOURCE=str(source),P14_POLICY=str(policy)),stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  try:
   for _ in range(80):
    try:urllib.request.urlopen(URL+'/api/session',timeout=1).close();break
    except Exception:await asyncio.sleep(.1)
   async with async_playwright()as p:
    browser=await p.chromium.launch(executable_path='/usr/bin/google-chrome',args=['--no-sandbox','--disable-gpu']);context=await browser.new_context(viewport={'width':1440,'height':1050});page=await context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)));frames=Path(directory)/'frames';frames.mkdir()
    async def capture():
     i=0
     while True:
      await page.screenshot(path=str(frames/f'{i:04d}.png'));i+=1;await asyncio.sleep(.5)
    recording=asyncio.create_task(capture())
    await page.goto(URL);await expect(page.locator('#status')).to_contain_text('CURRENT');await expect(page.locator('#quantities')).to_contain_text('18');await expect(page.locator('#quantities')).to_contain_text('12');await expect(page.locator('#confirmed-date')).to_contain_text('No single');checked('SO-A exact quantities, distinct dates and incomplete confirmation');await page.screenshot(path=str(out/'schedule-lines.png'),full_page=True)
    await page.locator('#lines button').first.focus();await page.keyboard.press('Enter');await expect(page.locator('#source-evidence')).to_contain_text('SRC-A-L1');assert await page.evaluate("document.activeElement.id")=='source-evidence';checked('Keyboard Enter opens named source destination')
    issued=asyncio.Event();gate=asyncio.Event()
    async def source_delay(route):response=await route.fetch();issued.set();await gate.wait();await route.fulfill(response=response)
    await page.route('**/api/source?*',source_delay);await page.locator('#lines button').first.click();await issued.wait();await page.locator('#order').focus();gate.set();await expect(page.locator('#source-evidence')).to_contain_text('SRC-A-L1');await asyncio.sleep(.1);assert await page.evaluate("document.activeElement.id")=='order';checked('Delayed source navigation preserves later explicit focus');await page.unroute('**/api/source?*',source_delay)
    await page.locator('#order').select_option('SO-C');await expect(page.locator('#heading')).to_contain_text('SO-C');await expect(page.locator('#event-summary')).to_have_text('3 unique source events · 1 transport duplicates · 2 instances · 1 active blocks');await expect(page.locator('#queue')).to_contain_text('BLK-C2');await expect(page.locator('#questions')).to_contain_text('Responsible role is unknown');await expect(page.locator('#history')).to_contain_text('fictional seeded');checked('Exact duplicate transport, current instance and seeded historical receipt')
    await page.locator('#revision').select_option('3');await expect(page.locator('#authority')).to_have_text('HISTORICAL SOURCE VIEW');await expect(page.locator('#review')).to_be_disabled();checked('Historical revision cannot authorize current review')
    await page.locator('#revision').select_option('4');await expect(page.locator('#authority')).to_have_text('CURRENT SOURCE VIEW');await page.locator('#confirm').check();await page.locator('#review').click();await expect(page.locator('#status')).to_contain_text('LOCAL REVIEW RECORDED');await expect(page.locator('#history')).to_contain_text('CURRENT LOCAL RECEIPT');await page.locator('#confirm').check();await page.locator('#review').click();await expect(page.locator('#status')).to_contain_text('existing receipt');assert await page.locator('#history p').count()==2;checked('Repeated acknowledgment is idempotent; block remains active');await expect(page.locator('#queue')).to_contain_text('BLK-C2');await page.screenshot(path=str(out/'event-handoff-review.png'),full_page=True)
    await page.locator('#confirm').check()
    async with page.expect_download()as download_info:await page.locator('#receipt').click()
    download=await download_info.value;await download.save_as(str(ROOT/'evidence/executed-local-receipt.json'));await expect(page.locator('#status')).to_contain_text('download completion');checked('Exact local receipt export scope; no target import/release claim')
    await page.locator('#role').select_option('Authorized Commercial Review');await expect(page.locator('#status')).to_contain_text('CURRENT');await page.locator('#order').select_option('SO-B');await expect(page.locator('#notes')).to_contain_text('Fictional commercial-only');await page.locator('#notes button').click();await expect(page.locator('#source-evidence')).to_contain_text('SYNTHETIC-B-CANARY');checked('Explicit fictional commercial projection can inspect its own source')
    issued=asyncio.Event();gate=asyncio.Event();delivered=asyncio.Event();captured=[]
    async def order_delay(route):response=await route.fetch();captured.append(await response.json());issued.set();await gate.wait();await route.fulfill(response=response);delivered.set()
    await page.route('**/api/order?*',order_delay,times=1);await page.locator('#refresh').click();await issued.wait();await page.locator('#role').select_option('Service');assert await page.locator('#desk').is_hidden();assert 'SYNTHETIC-B-CANARY'not in await page.locator('body').inner_text();gate.set();await delivered.wait();await expect(page.locator('#minimal')).to_be_visible();assert await page.locator('#desk').is_hidden();assert 'Fictional commercial-only'not in await page.locator('body').inner_text();assert await page.locator('#lines tr').count()==0;checked('Captured old commercial response cannot restore role-revoked evidence',{'old_payload_had_context':len(captured[0]['view']['restricted_context'])==1,'preserved_old_response_sha256':hashlib.sha256(json.dumps(captured[0],sort_keys=True).encode()).hexdigest()});(ROOT/'evidence/delayed-old-synthetic-response.json').write_text(json.dumps(captured[0],indent=2)+'\n');await page.screenshot(path=str(out/'permitted-status.png'),full_page=True)
    # A queued later selection must still apply desired role if earlier queued selection was skipped.
    await page.locator('#role').select_option('Authorized Commercial Review');await page.locator('#order').select_option('SO-A');await expect(page.locator('#heading')).to_contain_text('SO-A');assert await page.locator('#role').input_value()=='Authorized Commercial Review';checked('Rapid role/order choices reconcile desired server role before reads')
    await page.set_viewport_size({'width':390,'height':844});await page.screenshot(path=str(out/'mobile-390.png'),full_page=True);assert await page.evaluate('document.documentElement.scrollWidth<=innerWidth');sizes=await page.locator('table,button,label,pre,.subtle').evaluate_all("es=>es.filter(e=>e.getClientRects().length).map(e=>parseFloat(getComputedStyle(e).fontSize))");assert min(sizes)>=14;checked('390px readable native text and scrollable exact-key table',{'min_font_px':min(sizes),'no_page_overflow':True})
    await page.set_viewport_size({'width':1440,'height':1050});await page.locator('#order').select_option('SO-C');await expect(page.locator('#heading')).to_contain_text('SO-C');await page.locator('#confirm').check();source.rename(source.with_suffix('.held'));await page.locator('#refresh').click();await expect(page.locator('#status')).to_contain_text('authority revoked');await expect(page.locator('#review')).to_be_disabled();await expect(page.locator('#receipt')).to_be_disabled();assert not await page.locator('#confirm').is_checked();checked('Missing isolated source revokes current authority and actions');await page.screenshot(path=str(out/'source-unavailable.png'),full_page=True);source.with_suffix('.held').rename(source)
    await page.reload();await expect(page.locator('#status')).to_contain_text('CURRENT');policy.rename(policy.with_suffix('.held'));await page.locator('#refresh').click();await expect(page.locator('#status')).to_contain_text('authority revoked');checked('Missing isolated policy revokes all current evidence');policy.with_suffix('.held').rename(policy)
    await page.reload();await expect(page.locator('#status')).to_contain_text('CURRENT');await page.locator('#role').focus();await page.keyboard.press('Tab');assert await page.evaluate('document.activeElement.id')=='order';checked('Actual Tab sequence keeps named native controls');assert not errors;checked('No browser JavaScript errors');recording.cancel()
    try:await recording
    except asyncio.CancelledError:pass
    await context.close();await browser.close()
    subprocess.run(['ffmpeg','-y','-framerate','2','-i',str(frames/'%04d.png'),'-vf','scale=1440:1050:force_original_aspect_ratio=decrease,pad=1440:1050:(ow-iw)/2:(oh-ih)/2','-c:v','libx264','-crf','26','-pix_fmt','yuv420p',str(out/'cpu-native-demo.mp4')],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  finally:server.terminate();server.wait(timeout=5)
 assert hashlib.sha256(original.read_bytes()).hexdigest()==before
 evidence={'kind':'actual Chrome CPU engineering checks; no inference','model_calls':0,'source_sha256':before,'checks':checks,'passed':len(checks),'failed':0,'media':[{'path':str(path.relative_to(ROOT)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'bytes':path.stat().st_size}for path in sorted(out.glob('*.png'))]+[{'path':'docs/cpu-native-demo.mp4','sha256':hashlib.sha256((out/'cpu-native-demo.mp4').read_bytes()).hexdigest(),'bytes':(out/'cpu-native-demo.mp4').stat().st_size}]};(ROOT/'evidence/browser-checks.json').write_text(json.dumps(evidence,indent=2)+'\n');print(json.dumps({'passed':len(checks),'failed':0,'model_calls':0}))
if __name__=='__main__':asyncio.run(main())
