"""Actual local Chrome checks for versioned static overlay; original API, CPU only."""
import asyncio,json,os,shutil,subprocess,tempfile,urllib.request,hashlib
from pathlib import Path
from playwright.async_api import async_playwright,expect
ROOT=Path(__file__).resolve().parents[1];URL='http://127.0.0.1:5164'
async def main():
 checks=[];original=ROOT/'fixtures/source-v1.json';before=hashlib.sha256(original.read_bytes()).hexdigest();out=ROOT/'docs/ui-refit';out.mkdir(exist_ok=True)
 def checked(name,details=None):checks.append({'name':name,'passed':True,'details':details})
 with tempfile.TemporaryDirectory(prefix='p14-refit-owned-')as directory:
  source=Path(directory)/'source.json';policy=Path(directory)/'policy.json';shutil.copyfile(original,source);shutil.copyfile(ROOT/'fixtures/review-policy-v1.json',policy)
  server=subprocess.Popen(['node','--input-type=module','-e',"import {createRefit} from './ui-server-v2.mjs';(await createRefit({sourcePath:process.env.P14_SOURCE,policyPath:process.env.P14_POLICY})).listen(5164,'127.0.0.1')"],cwd=ROOT,env=dict(os.environ,P14_SOURCE=str(source),P14_POLICY=str(policy)),stdout=subprocess.DEVNULL,stderr=subprocess.PIPE)
  try:
   for _ in range(80):
    try:urllib.request.urlopen(URL+'/api/session',timeout=1).close();break
    except Exception:await asyncio.sleep(.1)
   async with async_playwright()as p:
    browser=await p.chromium.launch(executable_path='/usr/bin/google-chrome',args=['--no-sandbox','--disable-gpu']);context=await browser.new_context(viewport={'width':1440,'height':1050});page=await context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    async def shot(name):await page.screenshot(path=str(out/name),full_page=True)
    await page.goto(URL);await expect(page.locator('#status')).to_contain_text('CURRENT');await expect(page.locator('#quantities')).to_contain_text('18');await expect(page.locator('#quantities')).to_contain_text('12');await expect(page.locator('#confirmed-date')).to_contain_text('No single')
    left=await page.locator('#source-panel').bounding_box();right=await page.locator('#result-panel').bounding_box();assert abs(left['width']-right['width'])<1 and right['x']>left['x'];assert await page.locator('.page-title').text_content()=='주문 예외 인계 검토';checked('Equal white source/result panels, Korean title, exact schedule quantities and separate dates');await shot('01-current-lines.png')
    await page.locator('#lines button').first.focus();await page.keyboard.press('Enter');await expect(page.locator('#source-evidence')).to_contain_text('SRC-A-L1');assert await page.evaluate('document.activeElement.id')=='source-evidence';checked('Keyboard Enter opens original source evidence and moves focus');await shot('02-source-evidence.png')
    issued=asyncio.Event();gate=asyncio.Event()
    async def source_delay(route):response=await route.fetch();issued.set();await gate.wait();await route.fulfill(response=response)
    await page.route('**/api/source?*',source_delay);await page.locator('#lines button').first.click();await issued.wait();await page.locator('#order').focus();gate.set();await expect(page.locator('#source-evidence')).to_contain_text('SRC-A-L1');await asyncio.sleep(.1);assert await page.evaluate('document.activeElement.id')=='order';checked('Delayed source read preserves later explicit focus');await page.unroute('**/api/source?*',source_delay)
    await page.locator('#order').select_option('SO-C');await expect(page.locator('#heading')).to_contain_text('SO-C');await expect(page.locator('#event-summary')).to_have_text('3 unique source events · 1 transport duplicates · 2 instances · 1 active blocks');await expect(page.locator('#queue')).to_contain_text('BLK-C2');checked('C event fold deduplicates transport, retains two instances and active BLK-C2');await shot('03-event-fold.png')
    await expect(page.locator('#questions')).to_contain_text('Responsible role is unknown');await expect(page.locator('#queue')).to_contain_text('Unknown');await page.locator('#timeline button').last.click();await expect(page.locator('#source-evidence')).to_contain_text('EV-C3');checked('Unknown owner/questions stay unresolved beside exact EV-C3 original');await shot('04-unknown-owner.png')
    await page.locator('#revision').select_option('3');await expect(page.locator('#authority')).to_contain_text('HISTORICAL SOURCE VIEW');await expect(page.locator('#authority')).to_contain_text('CURRENT permission projection');await expect(page.locator('#review')).to_be_disabled();await expect(page.locator('#history')).to_contain_text('reviewed_at');await expect(page.locator('#history')).to_contain_text('2026-10-03T09:05:00+09:00');await expect(page.locator('#history')).to_contain_text('reviewer_role · 검토 역할: Unknown');checked('Historical source revision is distinct from current permission; seeded role remains unknown');await page.locator('.receipt-original').first.click();await expect(page.locator('#source-evidence')).to_contain_text('SEED-RR-C1');await expect(page.locator('#source-evidence')).to_contain_text('fixture_only');checked('Original seeded receipt drilldown preserves fictional origin and actual source fields');await shot('05-historical-receipt.png')
    await page.locator('#revision').select_option('4');await expect(page.locator('#authority')).to_contain_text('CURRENT SOURCE VIEW');stale=await page.evaluate("async()=>{let d=await(await fetch('/api/order?order=SO-C&revision=4')).json();return {...d.binding,acknowledgment:true}}")
    await page.locator('#confirm').check();await page.locator('#review').click();await expect(page.locator('#status')).to_contain_text('LOCAL REVIEW RECORDED');await expect(page.locator('#history')).to_contain_text('CURRENT LOCAL RECEIPT');await expect(page.locator('#history')).to_contain_text('reviewer_role · 검토 역할: Service');await page.locator('.receipt-original').last.click();await expect(page.locator('#source-evidence')).to_contain_text('executed_local_review');checked('Executed receipt displays timestamp/actual role and permits original drilldown');await page.locator('#confirm').check();await page.locator('#review').click();await expect(page.locator('#status')).to_contain_text('existing receipt');assert await page.locator('.receipt-row').count()==2;await expect(page.locator('#queue')).to_contain_text('BLK-C2');checked('Repeated acknowledgment returns one existing receipt without changing source block');await shot('06-repeated-review.png')
    await page.locator('#confirm').check()
    async with page.expect_download()as download_info:await page.locator('#receipt').click()
    download=await download_info.value;await download.save_as(str(out/'executed-local-receipt.json'));await expect(page.locator('#status')).to_contain_text('download completion');await expect(page.locator('#source-evidence')).to_contain_text('not_established');checked('Prepared receipt export preserves exact binding and bounded download/import claims');await shot('07-export-receipt.png')
    await page.locator('#role').select_option('Authorized Commercial Review');await expect(page.locator('#status')).to_contain_text('CURRENT');await page.locator('#order').select_option('SO-B');await expect(page.locator('#notes')).to_contain_text('Fictional commercial-only');await page.locator('#notes button').click();await expect(page.locator('#source-evidence')).to_contain_text('SYNTHETIC-B-CANARY');checked('Explicit commercial projection can inspect its own synthetic original source')
    issued=asyncio.Event();gate=asyncio.Event();delivered=asyncio.Event()
    async def order_delay(route):response=await route.fetch();issued.set();await gate.wait();await route.fulfill(response=response);delivered.set()
    await page.route('**/api/order?*',order_delay,times=1);await page.locator('#refresh').click();await issued.wait();await page.locator('#role').select_option('Service');assert await page.locator('#desk').is_hidden();assert 'SYNTHETIC-B-CANARY'not in await page.content();gate.set();await delivered.wait();await expect(page.locator('#minimal')).to_be_visible();assert await page.locator('#desk').is_hidden();assert 'Fictional commercial-only'not in await page.content();assert await page.locator('#lines tr').count()==0;assert await page.locator('.receipt-row').count()==0;checked('Role downgrade erases visible/hidden source and receipts; delayed old response cannot restore cache')
    projection=await page.evaluate("async()=>await(await fetch('/api/order?order=SO-B&revision=3')).json()");assert sorted(projection)==['owner_role','status'];checked('Service SO-B serialized historical read returns exactly status/owner_role with no metadata');await page.locator('#revision').select_option('3');await expect(page.locator('#status')).to_contain_text('HISTORICAL SOURCE VIEW');await expect(page.locator('#status')).to_contain_text('rev 3 / CURRENT permission projection');await shot('08-service-minimal.png');await page.locator('#revision').select_option('4');await expect(page.locator('#status')).to_contain_text('CURRENT SOURCE VIEW')
    rejected=await page.evaluate("async b=>{let r=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});return {status:r.status,body:await r.json()}}",stale);assert rejected['status']==409 and rejected['body']['error']=='STALE_REVIEW';checked('Old reviewed payload cannot survive role revision change')
    await page.locator('#role').select_option('Authorized Commercial Review');await page.locator('#order').select_option('SO-A');await expect(page.locator('#heading')).to_contain_text('SO-A');assert await page.locator('#role').input_value()=='Authorized Commercial Review';checked('Serialized rapid role/order selection reconciles desired role before read')
    await page.set_viewport_size({'width':390,'height':844});await shot('09-mobile-390.png');assert await page.evaluate('document.documentElement.scrollWidth<=innerWidth');sizes=await page.locator('table,button,label,pre,.scope').evaluate_all("es=>es.filter(e=>e.getClientRects().length).map(e=>parseFloat(getComputedStyle(e).fontSize))");assert min(sizes)>=14;title=await page.locator('.page-title').bounding_box();assert title['x']+title['width']<=390;assert await page.locator('.page-title').evaluate("e=>e.scrollWidth<=e.clientWidth");checked('390px single-line 28px title, readable controls, scrollable ledger and no page overflow',{'min_font_px':min(sizes),'no_page_overflow':True})
    await page.set_viewport_size({'width':1440,'height':1050});await page.locator('#order').select_option('SO-C');await expect(page.locator('#heading')).to_contain_text('SO-C');await page.locator('#confirm').check();source.rename(source.with_suffix('.held'));await page.locator('#refresh').click();await expect(page.locator('#status')).to_contain_text('authority revoked');await expect(page.locator('#review')).to_be_disabled();await expect(page.locator('#receipt')).to_be_disabled();assert not await page.locator('#confirm').is_checked();assert await page.locator('.receipt-row').count()==0;checked('Isolated missing source clears evidence/receipts and revokes acknowledgment/export');await shot('10-source-unavailable.png');source.with_suffix('.held').rename(source)
    restored=await page.evaluate("async b=>{let r=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});return {status:r.status,body:await r.json()}}",stale);assert restored['status']==409;checked('Restored source bytes cannot reaccept old payload without fresh session inspection')
    await page.reload();await expect(page.locator('#status')).to_contain_text('CURRENT');policy.rename(policy.with_suffix('.held'));await page.locator('#refresh').click();await expect(page.locator('#status')).to_contain_text('authority revoked');checked('Isolated missing policy revokes current authority');policy.with_suffix('.held').rename(policy)
    await page.reload();await expect(page.locator('#status')).to_contain_text('CURRENT');await page.locator('#role').focus();await page.keyboard.press('Tab');assert await page.evaluate('document.activeElement.id')=='order';checked('Actual Tab sequence follows named native controls');assert not errors;checked('No browser JavaScript errors');await browser.close()
  finally:server.terminate();server.wait(timeout=5)
 assert hashlib.sha256(original.read_bytes()).hexdigest()==before
 media=[{'path':str(path.relative_to(ROOT)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'bytes':path.stat().st_size,'origin':'actual Chrome screenshot' if path.suffix=='.png' else 'actual prepared local receipt export'}for path in sorted(out.glob('*'))if path.is_file()]
 evidence={'kind':'Actual local native Chrome CPU checks of UI v2; delegated original API','executed_in_CI':False,'model_calls':0,'source_sha256':before,'checks':checks,'passed':len(checks),'failed':0,'media':media,'original_video':'docs/cpu-native-demo.mp4 is historical pre-refit UI; not a current v2 capture'};(ROOT/'evidence/ui-refit-browser-checks.json').write_text(json.dumps(evidence,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'passed':len(checks),'failed':0,'screenshots':len(list(out.glob('*.png'))),'model_calls':0}))
if __name__=='__main__':asyncio.run(main())
